<a href="https://colab.research.google.com/github/Obi-chidinma2003/100-days-of-data-repository/blob/main/Day_11_Intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import sys
import numpy as np
import time

**BASIC NUMPY ARRAYS**

In [53]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [54]:
a =np.array([1,2,3,4])

In [55]:
b=np.array([0,-5, 1,1.5,2])

In [56]:
a[0],a[1]

(np.int64(1), np.int64(2))

In [57]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


**COMPARING MEMORY SPACE USED;LIST VERSUS NUMPY**

In [58]:
S = range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [59]:
D=np.arange(1000)
print(D.size*D.itemsize)

8000


*//AS SEEN ABOVE, NUMPY USES LESS MEMORY THAN A LIST//*

**COMPARING THE SPEED OF LIST VERSUS NUMPY**

In [60]:
SIZE=1000
L1=range(SIZE)
L2=range(SIZE)

In [61]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)

In [62]:
start=time.time()

**//calculating sum in a list//**

In [63]:
result=[(x,y) for x,y in zip(L1,L2)]

**TIME TAKEN FOR EXECUTION IN A LIST**

In [64]:
print((time.time()-start)*1000)

19.39535140991211


In [65]:
start=time.time()

//CALCULATING SUM IN NUMPY//

In [66]:
result=A1+A2
print((time.time()-start)*1000)

6.785869598388672
