<a href="https://colab.research.google.com/github/Obi-chidinma2003/100-days-of-data-repository/blob/main/Day_19_numpy_indexing_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTING NUMPY**

In [8]:
import numpy as np

**CREATING AND DEFINING our 1 Dimension ARRAYS**

In [9]:
array_1d =np.array([10,20,30,40,50])
array_1d

array([10, 20, 30, 40, 50])

**GETTING THE VALUES FROM THE ARRAY USING THEIR PLACE NUMBERS STARTING FROM [1]; [-1] REPRESENTS THE LAST VALUE IN THE ARRAY**

In [10]:
array_1d[-1]

np.int64(50)

In [11]:
array_1d[1:3]

array([20, 30])

**CREATING AND WORKING WITH TWO DIMENSIONAL ARRAY [1,2,3] signifies row 1, [4,5,6] signifies row 2, [7,8,9] signifies row 3**

In [13]:
array_2d=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Getting the value for row 1 column 2**

In [15]:
array_2d[1,2]

np.int64(6)

**Getting all the value in row two stopping at index two**

In [23]:
array_2d[:2,2]


array([3, 6])

**working with 3 Dimensional array**

In [27]:
array_3d=np.array([
    [  # Depth 0
        [1,2,3], # Row 0
       [4,5,6]  # Row 1

    ],
    [ # Depth 1
        [7,8,9],  # Row 0
        [10,11,12]  # Row 1


    ]
])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])



> **In depth one [1], of row zer [0], spot the second value [2]**



In [28]:
array_3d[1,0,2]

np.int64(9)

**Showing the values found in depth zero **

In [29]:
array_3d[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])